[package]
name = "dispatch"
version = "0.2.0"
edition = "2021"

[dependencies]
clap = { version = "4.1.6", features = ["derive"] }
csv = "1.2.0"
lettre = "0.10.3"
rpassword = "7.2.0"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.93"
